server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: login_route_1 # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: http://localhost:8001
          #uri: lb://CLOUD-GATEWAY-LOGIN-SERVICE #到註冊中心找服務
          predicates:
            - Path=/loginservice/route1/** # 断言，路径相匹配的进行路由

        - id: payment_route2
          uri: http://localhost:8001
          #uri: lb://CLOUD-GATEWAY-LOGIN-SERVICE
          predicates:
            - Path=/loginservice/route2/** #断言,路径相匹配的进行路由
          #  - After=2024-04-14T23:29:29.833059+08:00[Asia/Taipei]
          #  - Cookie=username,chunping   #带Cookie，并且username的值为chunping
          #- Header=X-Request-Id,\d+ #请求头要有 X-Request-Id属性并且值为整数的正则表达式


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/